#!/usr/bin/env node
/*
 * build-map.js — generate assets/nl-outline.js, the coastline the dashboard map
 * is drawn from.
 *
 * Source: Cartomap's WGS84 province boundaries for the Netherlands. Provinces
 * are used rather than a country outline because the IJsselmeer and Markermeer
 * belong to no province, so unioning them leaves those waters as holes — which
 * is exactly what matters here: several of the sites look north over them.
 *
 * Run this only when the outline needs regenerating; the result is committed.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const SOURCES = [
  'https://cartomap.github.io/nl/wgs84/provincie_2025.geojson',
  'https://cartomap.github.io/nl/wgs84/provincie_2024.geojson',
  'https://cartomap.github.io/nl/wgs84/provincie_2023.geojson',
  'https://cartomap.github.io/nl/wgs84/provincie_2022.geojson'
];

const TOLERANCE = 0.0035;   // degrees, ~250-400 m — finer than one screen pixel
const MIN_RING_AREA = 8e-5; // drop specks; keeps every Wadden island

// Perpendicular distance simplification (Douglas-Peucker).
function simplify(points, tol) {
  if (points.length < 4) return points;
  const sq = (a, b) => { const dx = a[0] - b[0], dy = a[1] - b[1]; return dx*dx + dy*dy; };
  function segDist(p, a, b) {
    let x = a[0], y = a[1], dx = b[0] - x, dy = b[1] - y;
    if (dx !== 0 || dy !== 0) {
      const t = ((p[0] - x) * dx + (p[1] - y) * dy) / (dx*dx + dy*dy);
      if (t > 1) { x = b[0]; y = b[1]; } else if (t > 0) { x += dx*t; y += dy*t; }
    }
    return sq(p, [x, y]);
  }
  const tol2 = tol * tol;
  function step(first, last, keep) {
    let maxD = tol2, idx = -1;
    for (let i = first + 1; i < last; i++) {
      const d = segDist(points[i], points[first], points[last]);
      if (d > maxD) { idx = i; maxD = d; }
    }
    if (idx === -1) return;
    step(first, idx, keep); keep.push(idx); step(idx, last, keep);
  }
  const keep = [0];
  step(0, points.length - 1, keep);
  keep.push(points.length - 1);
  keep.sort((a, b) => a - b);
  return keep.map((i) => points[i]);
}

function ringArea(ring) {
  let a = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    a += (ring[j][0] + ring[i][0]) * (ring[j][1] - ring[i][1]);
  }
  return Math.abs(a / 2);
}

async function main() {
  let geo = null, used = null;
  for (const url of SOURCES) {
    try {
      const r = await fetch(url);
      if (!r.ok) { console.warn(`${url} → HTTP ${r.status}`); continue; }
      geo = await r.json(); used = url; break;
    } catch (e) { console.warn(`${url} → ${e.message}`); }
  }
  if (!geo) throw new Error('No source reachable.');
  console.log('Source:', used);

  const rings = [];
  for (const f of geo.features || []) {
    const g = f.geometry;
    if (!g) continue;
    const polys = g.type === 'Polygon' ? [g.coordinates]
      : g.type === 'MultiPolygon' ? g.coordinates : [];
    for (const poly of polys) {
      for (const ring of poly) {
        if (ringArea(ring) < MIN_RING_AREA) continue;
        const s = simplify(ring.map((p) => [p[0], p[1]]), TOLERANCE);
        if (s.length < 5) continue;
        rings.push(s.map((p) => [Math.round(p[0] * 1e4) / 1e4, Math.round(p[1] * 1e4) / 1e4]));
      }
    }
  }
  rings.sort((a, b) => ringArea(b) - ringArea(a));

  let minLon = 180, maxLon = -180, minLat = 90, maxLat = -90, points = 0;
  for (const r of rings) for (const [lon, lat] of r) {
    points++;
    if (lon < minLon) minLon = lon; if (lon > maxLon) maxLon = lon;
    if (lat < minLat) minLat = lat; if (lat > maxLat) maxLat = lat;
  }

  const out = {
    source: used,
    bbox: [minLon, minLat, maxLon, maxLat],
    rings
  };
  const js = '/* Generated by scripts/build-map.js — do not edit by hand.\n'
    + ' * Coastline and province outlines of the Netherlands, simplified to ~350 m.\n'
    + ` * Source: ${used}\n */\n`
    + '(function (root, data) {\n'
    + '  if (typeof module === "object" && module.exports) module.exports = data;\n'
    + '  root.NL_OUTLINE = data;\n'
    + '})(typeof globalThis !== "undefined" ? globalThis : this, '
    + JSON.stringify(out) + ');\n';

  const dest = path.join(__dirname, '..', 'assets', 'nl-outline.js');
  fs.writeFileSync(dest, js);
  console.log(`rings: ${rings.length}, points: ${points}, bbox: ${out.bbox.join(', ')}`);
  console.log(`wrote ${path.relative(path.join(__dirname, '..'), dest)} (${Math.round(fs.statSync(dest).size/1024)} kB)`);
}

main().catch((e) => { console.error(e.message); process.exit(1); });
